export {default as Home} from './Home'
export {default as Nook} from './Nook'
export {default as UpdateProfile} from './UpdateProfile'
export {default as Writing} from './Writing'
export {default as About} from './About'